import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('imports a file, builds a graph, saves and reopens a project, then exports', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Variables' })).toBeVisible()
  if (process.env.GB_CAPTURE_GUIDE === '1') {
    await page.setViewportSize({ width: 1440, height: 900 })
    await expect(page.getByRole('region', { name: 'Graph preview' })).toBeVisible()
    await expect(page.locator('.interactive-legend')).toBeVisible()
    await page.screenshot({ path: 'docs/screenshots/workspace.png', fullPage: false })
    await page.getByRole('button', { name: 'Projects & export' }).click()
    await page.screenshot({ path: 'docs/screenshots/projects.png', fullPage: false })
    await page.getByRole('button', { name: 'Close projects' }).click()
  }
  page.once('dialog', (dialog) => dialog.accept())
  await page.locator('input[type="file"][accept*=".csv"]').first().setInputFiles({ name: 'sample-study.csv', mimeType: 'text/csv', buffer: Buffer.from('Pressure,Dose,Group\n10,20,A\n10,40,A\n30,70,B\n') })
  await expect(page.getByText('sample-study', { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('region', { name: 'Graph preview' })).toContainText('3 source rows')
  await page.getByRole('button', { name: 'View data table' }).click()
  await expect(page.getByRole('dialog', { name: 'sample-study' })).toContainText('3 of 3 rows')
  const doseCell = page.locator('.ag-row[row-index="0"] .ag-cell[col-id="dose_1"]')
  await doseCell.dblclick()
  await page.locator('.ag-cell-inline-editing input').fill('25')
  await page.locator('.ag-cell-inline-editing input').press('Enter')
  await expect(doseCell).toContainText('25')
  await page.getByRole('button', { name: 'Close data table' }).click()
  await page.locator('.variable-list').getByRole('button', { name: 'Group', exact: true }).click()
  await page.getByLabel('Assign selected column to').selectOption('color')
  await page.getByRole('button', { name: 'Assign', exact: true }).click()
  await page.getByRole('button', { name: 'Filter selected column' }).click()
  await page.getByRole('dialog', { name: 'Group' }).getByLabel('B').uncheck()
  await page.getByRole('button', { name: 'Apply filter' }).click()
  await expect(page.getByText('1 active')).toBeVisible()
  await page.getByRole('button', { name: /Bars$/ }).first().click()
  await page.getByLabel('Error bars').selectOption('sd')
  await expect(page.getByRole('region', { name: 'Graph preview' })).toBeVisible()
  await page.getByRole('button', { name: 'Projects & export' }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download project' }).click()
  const project = await download
  expect(project.suggestedFilename()).toMatch(/\.graphbuilder$/)
  await page.getByRole('button', { name: 'Close projects' }).click()
  await page.getByRole('button', { name: 'Projects & export' }).click()
  await page.locator('input[type="file"][accept*=".json"]').first().setInputFiles(await project.path())
  await expect(page.getByRole('dialog', { name: /Save before opening/ })).toBeVisible()
  const backupDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Save current project and open' }).click()
  expect((await backupDownload).suggestedFilename()).toMatch(/\.graphbuilder$/)
  await expect(page.getByLabel('Error bars')).toHaveValue('sd')
  await page.getByRole('button', { name: 'View data table' }).click()
  await expect(page.getByRole('dialog', { name: 'sample-study' })).toContainText('2 of 3 rows')
  await expect(page.locator('.ag-row[row-index="0"] .ag-cell[col-id="dose_1"]')).toContainText('25')
  await page.getByRole('button', { name: 'Close data table' }).click()
  await page.getByRole('button', { name: 'Projects & export' }).click()
  const csvDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export plotted data CSV' }).click()
  const exported = await csvDownload
  expect(exported.suggestedFilename()).toContain('.csv')
  expect(await readFile(await exported.path(), 'utf8')).toContain('10.606601717798213')
})

test('opening a project can be canceled, saved, undone, and redone; invalid files show a dialog', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Projects & export' }).click()
  const firstDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download project' }).click()
  const exampleProject = await firstDownload
  await page.getByRole('button', { name: 'Close projects' }).click()

  page.once('dialog', (dialog) => dialog.accept())
  await page.locator('input[type="file"][accept*=".csv"]').first().setInputFiles({ name: 'my-work.csv', mimeType: 'text/csv', buffer: Buffer.from('X,Y\n1,2\n3,4\n') })
  await expect(page.getByText('my-work', { exact: true }).first()).toBeVisible()

  await page.getByRole('button', { name: 'Projects & export' }).click()
  const projectInput = page.getByLabel('Choose a project file')
  await projectInput.setInputFiles(await exampleProject.path())
  await page.getByRole('button', { name: 'Cancel opening' }).click()
  await page.getByRole('button', { name: 'Close projects' }).click()
  await expect(page.getByText('my-work', { exact: true }).first()).toBeVisible()

  await page.getByRole('button', { name: 'Projects & export' }).click()
  await projectInput.setInputFiles(await exampleProject.path())
  const backup = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Save current project and open' }).click()
  expect((await backup).suggestedFilename()).toBe('my-work.graphbuilder')
  await expect(page.getByText('my-work', { exact: true })).toHaveCount(0)
  await page.keyboard.press('Control+z')
  await expect(page.getByText('my-work', { exact: true }).first()).toBeVisible()
  await page.keyboard.press('Control+y')
  await expect(page.getByText('my-work', { exact: true })).toHaveCount(0)

  await page.getByRole('button', { name: 'Projects & export' }).click()
  await projectInput.setInputFiles({ name: 'broken.graphbuilder', mimeType: 'application/json', buffer: Buffer.from('{not valid JSON') })
  await expect(page.getByRole('alertdialog', { name: 'Could not open project' })).toContainText('not valid JSON')
  await page.getByRole('button', { name: 'Keep current project' }).click()
  await expect(page.getByRole('heading', { name: 'Projects' })).toBeVisible()
})
