import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('imports a file, builds a graph, saves and reopens a project, then exports', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Variables' })).toBeVisible()
  if (process.env.GB_CAPTURE_GUIDE === '1') {
    await expect(page.getByRole('region', { name: 'Graph preview' })).toBeVisible()
    await page.screenshot({ path: 'docs/screenshots/workspace.png', fullPage: false })
    await page.getByRole('button', { name: 'Projects & export' }).click()
    await page.screenshot({ path: 'docs/screenshots/projects.png', fullPage: false })
    await page.getByRole('button', { name: 'Close projects' }).click()
  }
  page.once('dialog', (dialog) => dialog.accept())
  await page.locator('input[type="file"][accept*=".csv"]').first().setInputFiles({ name: 'sample-study.csv', mimeType: 'text/csv', buffer: Buffer.from('Pressure,Dose,Group\n10,20,A\n10,40,A\n30,70,B\n') })
  await expect(page.getByText('sample-study', { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('region', { name: 'Graph preview' })).toContainText('3 source rows')
  await page.getByRole('button', { name: 'View data table' }).click()
  await expect(page.getByRole('dialog', { name: 'sample-study' })).toContainText('3 of 3 rows')
  const doseCell = page.locator('.ag-row[row-index="0"] .ag-cell[col-id="dose_1"]')
  await doseCell.dblclick()
  await page.locator('.ag-cell-inline-editing input').fill('25')
  await page.locator('.ag-cell-inline-editing input').press('Enter')
  await expect(doseCell).toContainText('25')
  await page.getByRole('button', { name: 'Close data table' }).click()
  await page.getByRole('button', { name: 'Group', exact: true }).click()
  await page.getByLabel('Assign selected column to').selectOption('color')
  await page.getByRole('button', { name: 'Assign', exact: true }).click()
  await page.getByRole('button', { name: 'Filter selected column' }).click()
  await page.getByRole('dialog', { name: 'Group' }).getByLabel('B').uncheck()
  await page.getByRole('button', { name: 'Apply filter' }).click()
  await expect(page.getByText('1 active')).toBeVisible()
  await page.getByRole('button', { name: /Bars$/ }).first().click()
  await page.getByLabel('Error bars').selectOption('sd')
  await expect(page.getByRole('region', { name: 'Graph preview' })).toBeVisible()
  await page.getByRole('button', { name: 'Projects & export' }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download project' }).click()
  const project = await download
  expect(project.suggestedFilename()).toContain('.graphbuilder.json')
  await page.getByRole('button', { name: 'Close projects' }).click()
  await page.getByRole('button', { name: 'Projects & export' }).click()
  page.once('dialog', (dialog) => dialog.accept())
  await page.locator('input[type="file"][accept*=".json"]').first().setInputFiles(await project.path())
  await page.getByRole('button', { name: 'Projects & export' }).click()
  await expect(page.getByRole('heading', { name: 'Projects' })).toBeVisible()
  await page.getByRole('button', { name: 'Close projects' }).click()
  await expect(page.getByLabel('Error bars')).toHaveValue('sd')
  await page.getByRole('button', { name: 'View data table' }).click()
  await expect(page.getByRole('dialog', { name: 'sample-study' })).toContainText('2 of 3 rows')
  await expect(page.locator('.ag-row[row-index="0"] .ag-cell[col-id="dose_1"]')).toContainText('25')
  await page.getByRole('button', { name: 'Close data table' }).click()
  await page.getByRole('button', { name: 'Projects & export' }).click()
  const csvDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export plotted data CSV' }).click()
  const exported = await csvDownload
  expect(exported.suggestedFilename()).toContain('.csv')
  expect(await readFile(await exported.path(), 'utf8')).toContain('10.606601717798213')
})
