import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('imports a file, builds a graph, saves and reopens a project, then exports', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Variables' })).toBeVisible()
  if (process.env.GB_CAPTURE_GUIDE === '1') {
    await page.setViewportSize({ width: 1440, height: 900 })
    await expect(page.getByRole('region', { name: 'Graph preview' })).toBeVisible()
    await expect(page.locator('.interactive-legend')).toBeVisible()
    await page.screenshot({ path: 'docs/screenshots/workspace.png', fullPage: false })
    await page.getByRole('button', { name: 'Projects & export' }).click()
    await page.screenshot({ path: 'docs/screenshots/projects.png', fullPage: false })
    await page.getByRole('button', { name: 'Close projects' }).click()
  }
  page.once('dialog', (dialog) => dialog.accept())
  await page.locator('input[type="file"][accept*=".csv"]').first().setInputFiles({ name: 'sample-study.csv', mimeType: 'text/csv', buffer: Buffer.from('Pressure,Dose,Group\n10,20,A\n10,40,A\n30,70,B\n') })
  await page.getByRole('button', { name: 'Import selected data' }).click()
  await expect(page.getByText('sample-study', { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('region', { name: 'Graph preview' })).toContainText('3 source rows')
  await page.getByRole('button', { name: 'View data table' }).click()
  await expect(page.getByRole('dialog', { name: 'sample-study' })).toContainText('3 of 3 rows')
  const doseCell = page.locator('.ag-row[row-index="0"] .ag-cell[col-id="dose_1"]')
  await doseCell.dblclick()
  await page.locator('.ag-cell-inline-editing input').fill('25')
  await page.locator('.ag-cell-inline-editing input').press('Enter')
  await expect(doseCell).toContainText('25')
  await page.getByRole('button', { name: 'Close data table' }).click()
  await page.locator('.variable-list').getByRole('button', { name: 'Group', exact: true }).click()
  await page.getByLabel('Assign selected column to').selectOption('color')
  await page.getByRole('button', { name: 'Assign', exact: true }).click()
  await page.getByRole('button', { name: 'Filter selected column' }).click()
  await page.getByRole('dialog', { name: 'Group' }).getByLabel('B').uncheck()
  await page.getByRole('button', { name: 'Apply filter' }).click()
  await expect(page.getByText('1 active')).toBeVisible()
  await page.getByRole('button', { name: /Bars$/ }).first().click()
  await page.getByLabel('Error bars').selectOption('sd')
  await expect(page.getByRole('region', { name: 'Graph preview' })).toBeVisible()
  await page.getByRole('button', { name: 'Projects & export' }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download project' }).click()
  const project = await download
  expect(project.suggestedFilename()).toMatch(/\.graphbuilder$/)
  await page.getByRole('button', { name: 'Close projects' }).click()
  await page.getByRole('button', { name: 'Projects & export' }).click()
  await page.locator('input[type="file"][accept*=".json"]').first().setInputFiles(await project.path())
  await expect(page.getByRole('dialog', { name: /Save before opening/ })).toHaveCount(0)
  await expect(page.getByLabel('Error bars')).toHaveValue('sd')
  await page.getByRole('button', { name: 'View data table' }).click()
  await expect(page.getByRole('dialog', { name: 'sample-study' })).toContainText('2 of 3 rows')
  await expect(page.locator('.ag-row[row-index="0"] .ag-cell[col-id="dose_1"]')).toContainText('25')
  await page.getByRole('button', { name: 'Close data table' }).click()
  await page.getByRole('button', { name: 'Projects & export' }).click()
  const csvDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export plotted data CSV' }).click()
  const exported = await csvDownload
  expect(exported.suggestedFilename()).toContain('.csv')
  expect(await readFile(await exported.path(), 'utf8')).toContain('10.606601717798213')
})

test('opening a project can be canceled, saved, undone, and redone; invalid files show a dialog', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Projects & export' }).click()
  const firstDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download project' }).click()
  const exampleProject = await firstDownload
  await page.getByRole('button', { name: 'Close projects' }).click()

  page.once('dialog', (dialog) => dialog.accept())
  await page.locator('input[type="file"][accept*=".csv"]').first().setInputFiles({ name: 'my-work.csv', mimeType: 'text/csv', buffer: Buffer.from('X,Y\n1,2\n3,4\n') })
  await page.getByRole('button', { name: 'Import selected data' }).click()
  await expect(page.getByText('my-work', { exact: true }).first()).toBeVisible()

  await page.getByRole('button', { name: 'Projects & export' }).click()
  const projectInput = page.getByLabel('Choose a project file')
  await projectInput.setInputFiles(await exampleProject.path())
  await page.getByRole('button', { name: 'Cancel opening' }).click()
  await page.getByRole('button', { name: 'Close projects' }).click()
  await expect(page.getByText('my-work', { exact: true }).first()).toBeVisible()

  await page.getByRole('button', { name: 'Projects & export' }).click()
  await projectInput.setInputFiles(await exampleProject.path())
  const backup = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Save current project and open' }).click()
  expect((await backup).suggestedFilename()).toBe('my-work.graphbuilder')
  await expect(page.getByText('my-work', { exact: true })).toHaveCount(0)
  await page.keyboard.press('Control+z')
  await expect(page.getByText('my-work', { exact: true }).first()).toBeVisible()
  await page.keyboard.press('Control+y')
  await expect(page.getByText('my-work', { exact: true })).toHaveCount(0)

  await page.getByRole('button', { name: 'Projects & export' }).click()
  await projectInput.setInputFiles({ name: 'broken.graphbuilder', mimeType: 'application/json', buffer: Buffer.from('{not valid JSON') })
  await expect(page.getByRole('alertdialog', { name: 'Could not open project' })).toContainText('not valid JSON')
  await page.getByRole('button', { name: 'Keep current project' }).click()
  await expect(page.getByRole('heading', { name: 'Projects' })).toBeVisible()
})

test('editing after a project download restores the save-before-opening prompt', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Projects & export' }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download project' }).click()
  const savedProject = await download
  await page.getByRole('button', { name: 'Close projects' }).click()

  await page.getByRole('button', { name: 'View data table' }).click()
  const firstDose = page.locator('.ag-row[row-index="0"] .ag-cell[col-id="dose"]')
  await firstDose.dblclick()
  await page.locator('.ag-cell-inline-editing input').fill('999')
  await page.locator('.ag-cell-inline-editing input').press('Enter')
  await page.getByRole('button', { name: 'Close data table' }).click()

  await page.getByRole('button', { name: 'Projects & export' }).click()
  await page.getByLabel('Choose a project file').setInputFiles(await savedProject.path())
  await expect(page.getByRole('dialog', { name: /Save before opening/ })).toBeVisible()
  await page.getByRole('button', { name: 'Discard edits and open' }).click()
  await page.getByRole('button', { name: 'View data table' }).click()
  await expect(page.locator('.ag-row[row-index="0"] .ag-cell[col-id="dose"]')).not.toContainText('999')
})

test('the untouched example opens a project without a save prompt', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Projects & export' }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download project' }).click()
  const exampleProject = await download
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Variables' })).toBeVisible()

  await page.getByRole('button', { name: 'Projects & export' }).click()
  await page.getByLabel('Choose a project file').setInputFiles(await exampleProject.path())
  await expect(page.getByRole('dialog', { name: /Save before opening/ })).toHaveCount(0)
  await expect(page.getByRole('dialog', { name: 'Projects' })).toHaveCount(0)
})

test('Reset example can be undone and redone', async ({ page }) => {
  await page.goto('/')
  page.once('dialog', (dialog) => dialog.accept())
  await page.locator('input[type="file"][accept*=".csv"]').first().setInputFiles({ name: 'reset-test.csv', mimeType: 'text/csv', buffer: Buffer.from('X,Y\n1,2\n3,4\n') })
  await page.getByRole('button', { name: 'Import selected data' }).click()
  await expect(page.getByRole('region', { name: 'Graph preview' })).toContainText('reset-test. 2 source rows')
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Reset example' }).click()
  await expect(page.getByRole('region', { name: 'Graph preview' })).toContainText('45 source rows')
  await page.keyboard.press('Control+z')
  await expect(page.getByRole('region', { name: 'Graph preview' })).toContainText('reset-test. 2 source rows')
  await page.keyboard.press('Control+y')
  await expect(page.getByRole('region', { name: 'Graph preview' })).toContainText('45 source rows')
})

test('a linked project shows its data mode when reopened', async ({ page }) => {
  await page.goto('/')
  const source = { name: 'linked-data.csv', mimeType: 'text/csv', buffer: Buffer.from('Study results\nX,Y\n1,2\n3,4\n') }
  page.once('dialog', (dialog) => dialog.accept())
  await page.locator('input[type="file"][accept*=".csv"]').first().setInputFiles(source)
  await page.getByRole('spinbutton', { name: 'Rows to skip before header' }).fill('1')
  await page.getByRole('button', { name: 'Import selected data' }).click()
  await page.getByRole('button', { name: 'Projects & export' }).click()
  const projects = page.getByRole('dialog', { name: 'Projects' })
  await expect(projects.getByText('Current project:')).toContainText('Embedded')
  await projects.getByLabel('Data in saved file').selectOption('linked')
  const download = page.waitForEvent('download')
  await projects.getByRole('button', { name: 'Download project' }).click()
  const linkedProject = await download
  await projects.getByRole('button', { name: 'Close projects' }).click()

  await page.getByRole('button', { name: 'Projects & export' }).click()
  await page.getByLabel('Choose a project file').setInputFiles(await linkedProject.path())
  await expect(page.getByText('Last found at linked-data.csv (folder path unavailable in the browser)')).toBeVisible()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  const linkedContent = JSON.parse(await readFile(await linkedProject.path(), 'utf8'))
  expect(linkedContent.data.source.skipRows).toBe(1)
  linkedContent.data.source.nativePath = 'C:\\Studies\\linked-data.csv'
  await page.getByLabel('Choose a project file').setInputFiles({ name: 'linked-data.graphbuilder', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(linkedContent)) })
  await expect(page.getByText('Last found at C:\\Studies\\linked-data.csv')).toBeVisible()
  await page.getByLabel('Choose linked source data').setInputFiles(source)
  await page.getByRole('button', { name: 'Projects & export' }).click()
  await expect(page.getByRole('dialog', { name: 'Projects' }).getByText('Current project:')).toContainText('Linked')
  await expect(page.getByLabel('Data in saved file')).toHaveValue('linked')
})

test('dropping a project file opens it through the save-or-discard flow', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Projects & export' }).click()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download project' }).click()
  const project = await download
  await page.getByRole('button', { name: 'Close projects' }).click()

  page.once('dialog', (dialog) => dialog.accept())
  await page.locator('input[type="file"][accept*=".csv"]').first().setInputFiles({ name: 'dropped-work.csv', mimeType: 'text/csv', buffer: Buffer.from('X,Y\n1,2\n') })
  await page.getByRole('button', { name: 'Import selected data' }).click()
  const content = await readFile(await project.path(), 'utf8')
  await page.evaluate((projectContent) => {
    const transfer = new DataTransfer()
    transfer.items.add(new File([projectContent], 'example.graphbuilder', { type: 'application/json' }))
    window.dispatchEvent(new DragEvent('dragenter', { bubbles: true, dataTransfer: transfer }))
    window.dispatchEvent(new DragEvent('drop', { bubbles: true, dataTransfer: transfer }))
  }, content)
  await expect(page.getByRole('dialog', { name: /Save before opening/ })).toBeVisible()
  await page.getByRole('button', { name: 'Discard edits and open' }).click()
  await expect(page.getByText('dropped-work', { exact: true })).toHaveCount(0)
})
