import { expect, test } from '@playwright/test'

test('question mark opens compact keyboard help and returns focus on close', async ({ page }) => {
  await page.goto('/')
  const projects = page.getByRole('button', { name: 'Projects & export' })
  await projects.focus()
  await page.keyboard.press('Shift+/')
  const help = page.getByRole('dialog', { name: 'Keyboard shortcuts' })
  await expect(help).toBeVisible()
  await expect(help.getByText('Undo / redo outside text fields')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Close keyboard shortcuts' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(help).toHaveCount(0)
  await expect(projects).toBeFocused()

  const search = page.getByPlaceholder('Search variables')
  await search.focus()
  await page.keyboard.type('?')
  await expect(search).toHaveValue('?')
  await expect(help).toHaveCount(0)
})

test('Ctrl+N adds an empty graph to the current project', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Variables' })).toBeVisible()
  await page.getByRole('button', { name: 'Projects & export' }).focus()
  await page.keyboard.press('Control+n')
  await expect(page.getByRole('region', { name: 'Graph preview' })).toContainText('Build a graph')
  await page.getByRole('button', { name: 'Projects & export' }).click()
  await expect(page.getByRole('button', { name: 'New graph · open' })).toBeVisible()
  await expect(page.locator('.project-graph-list').first().getByRole('button')).toHaveCount(4)
})

test('mouse Back and Forward undo and redo graph changes', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Projects & export' }).focus()
  await page.keyboard.press('Control+n')
  await expect(page.getByRole('region', { name: 'Graph preview' })).toContainText('Build a graph')
  await page.evaluate(() => document.body.dispatchEvent(new MouseEvent('mousedown', { bubbles: true, cancelable: true, button: 3 })))
  await expect(page.getByRole('region', { name: 'Graph preview' })).not.toContainText('Build a graph')
  await page.evaluate(() => document.body.dispatchEvent(new MouseEvent('mousedown', { bubbles: true, cancelable: true, button: 4 })))
  await expect(page.getByRole('region', { name: 'Graph preview' })).toContainText('Build a graph')
})

test('Ctrl+D opens the data table and suggested-layer feedback fades away', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Projects & export' }).focus()
  await page.keyboard.press('Control+d')
  await expect(page.getByRole('dialog', { name: 'Example measurements (synthetic data)' })).toBeVisible()
  await page.getByRole('button', { name: 'Close data table' }).click()
  await page.getByRole('button', { name: /Bars$/ }).first().click()
  await page.locator('.suggest-button').click()
  await expect(page.locator('.compatibility-message.transient')).toBeVisible()
  await expect(page.locator('.compatibility-message')).toHaveCount(0, { timeout: 6500 })
})
