import { expect, test } from '@playwright/test'

test('question mark opens compact keyboard help and returns focus on close', async ({ page }) => {
  await page.goto('/')
  const projects = page.getByRole('button', { name: 'Projects & export' })
  await projects.focus()
  await page.keyboard.press('Shift+/')
  const help = page.getByRole('dialog', { name: 'Keyboard shortcuts' })
  await expect(help).toBeVisible()
  await expect(help.getByText('Undo / redo outside text fields')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Close keyboard shortcuts' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(help).toHaveCount(0)
  await expect(projects).toBeFocused()

  const search = page.getByPlaceholder('Search variables')
  await search.focus()
  await page.keyboard.type('?')
  await expect(search).toHaveValue('?')
  await expect(help).toHaveCount(0)
})

test('browser shortcut help omits browser-reserved shortcuts', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Keyboard shortcuts' }).click()
  const help = page.getByRole('dialog', { name: 'Keyboard shortcuts' })
  await expect(help).toBeVisible()
  await expect(help.getByText('Ctrl+N')).toHaveCount(0)
  await expect(help.getByText('Ctrl+D')).toHaveCount(0)
  await expect(help.getByText('Mouse Back / Forward')).toHaveCount(0)
  await expect(help.getByText('Ctrl+Z / Ctrl+Y')).toBeVisible()
})

test('mouse Back and Forward undo and redo graph changes', async ({ page }) => {
  await page.goto('/')
  const projects = page.getByRole('button', { name: 'Projects & export' })
  await projects.focus()
  await projects.click()
  await page.getByRole('button', { name: /New graph/ }).first().click()
  await page.getByRole('button', { name: 'Close projects' }).click()
  await expect(page.getByRole('region', { name: 'Graph preview' })).toContainText('Build a graph')
  const bounds = await projects.boundingBox()
  expect(bounds).not.toBeNull()
  const mouse = await page.context().newCDPSession(page)
  const x = bounds!.x + bounds!.width / 2
  const y = bounds!.y + bounds!.height / 2
  await mouse.send('Input.dispatchMouseEvent', { type: 'mousePressed', x, y, button: 'back', clickCount: 1 })
  await mouse.send('Input.dispatchMouseEvent', { type: 'mouseReleased', x, y, button: 'back', clickCount: 1 })
  await expect(page.getByRole('region', { name: 'Graph preview' })).not.toContainText('Build a graph')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await mouse.send('Input.dispatchMouseEvent', { type: 'mousePressed', x, y, button: 'forward', clickCount: 1 })
  await mouse.send('Input.dispatchMouseEvent', { type: 'mouseReleased', x, y, button: 'forward', clickCount: 1 })
  await expect(page.getByRole('region', { name: 'Graph preview' })).toContainText('Build a graph')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.evaluate(() => {
    const button = Array.from(document.querySelectorAll('button')).find((item) => item.textContent === 'Projects & export')
    if (!button) throw new Error('Projects button not found')
    button.dispatchEvent(new MouseEvent('mousedown', { bubbles: true, cancelable: true, button: 3 }))
    button.dispatchEvent(new MouseEvent('mouseup', { bubbles: true, cancelable: true, button: 3 }))
    button.dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true, button: 0 }))
  })
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('mouse Back over a graph point does not select it or start box selection', async ({ page }) => {
  await page.goto('/')
  const point = page.locator('.plotly-chart .scatterlayer .point').first()
  await expect(point).toBeVisible()
  const bounds = await point.boundingBox()
  expect(bounds).not.toBeNull()
  const x = bounds!.x + bounds!.width / 2
  const y = bounds!.y + bounds!.height / 2
  const mouse = await page.context().newCDPSession(page)
  await mouse.send('Input.dispatchMouseEvent', { type: 'mousePressed', x, y, button: 'back', clickCount: 1 })
  await mouse.send('Input.dispatchMouseEvent', { type: 'mouseMoved', x: x + 25, y: y + 25, button: 'back', buttons: 8 })
  await mouse.send('Input.dispatchMouseEvent', { type: 'mouseReleased', x: x + 25, y: y + 25, button: 'back', clickCount: 1 })
  await expect(page.locator('.graph-selection-bar')).toHaveCount(0)
  await expect(page.locator('.select-outline')).toHaveCount(0)
  await page.mouse.click(x, y)
  await expect(page.locator('.graph-selection-bar')).toBeVisible()
})

test('data table button opens the table and suggested-layer feedback fades away', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'View data table' }).click()
  await expect(page.getByRole('dialog', { name: 'Example measurements (synthetic data)' })).toBeVisible()
  await page.getByRole('button', { name: 'Close data table' }).click()
  await page.getByRole('button', { name: /Bars$/ }).first().click()
  await page.locator('.suggest-button').click()
  await expect(page.locator('.compatibility-message.transient')).toBeVisible()
  await expect(page.locator('.compatibility-message')).toHaveCount(0, { timeout: 6500 })
})
